<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class QuestionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('questions')->delete();
        
        \DB::table('questions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'created_by' => 13,
            'question' => 'Thủ đô Mỹ? (Đã sửa)',
                'answerA' => 'DC',
                'answerB' => 'New York',
                'answerC' => 'Vegas',
                'answerD' => 'Cali',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-02-24 21:35:02',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'created_by' => 13,
                'question' => 'Thủ đô Việt nam?',
                'answerA' => 'Hà Nội',
                'answerB' => 'Hà Tĩnh',
                'answerC' => 'Hà Nam',
                'answerD' => 'Hồ Chí Minh',
                'correctAnswer' => 'B',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Thủ đô của Việt Nam là Hà Nội',
                'exam_id' => 1,
                'created_at' => NULL,
                'updated_at' => '2022-02-24 21:32:44',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 173,
                'created_by' => 13,
                'question' => 'PostBack có cho Form nào dưới đây',
                'answerA' => ' Winforms',
                'answerB' => 'HTMLForms',
                'answerC' => 'Webforms',
                'answerD' => 'Cả 3 câu a,b,c đều đúng',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 174,
                'created_by' => 13,
                'question' => 'Ứng dụng web ?',
                'answerA' => 'Chỉ chạy trên một máy đơn',
                'answerB' => 'Có kiến trúc Client/Server',
                'answerC' => 'Là tất cả ứng dụng có sử dụng Internet',
                'answerD' => 'Cả 2 câu a và b đều sai',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 175,
                'created_by' => 13,
                'question' => 'Địa chỉ URL của ứng dụng web được xác định bởi ?',
                'answerA' => 'Thư mục ảo của ứng dụng',
                'answerB' => 'Thư mục vật lý của ứng dụng',
                'answerC' => 'Tên của Project',
                'answerD' => 'Cả 3 câu đều sai',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 176,
                'created_by' => 13,
                'question' => 'Phát biểu nào đúng ?',
                'answerA' => 'Phần thực thi của ứng dụng web chạy dưới sự điều khiển của web server',
                'answerB' => 'Thông tin được truyền từ server đến client bằng giao thức FTP',
                'answerC' => 'Ứng dụng web không cần phải cài đặt trên phía client',
                'answerD' => 'Dịch vụ web là một loại ứng dụng Internet',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 177,
                'created_by' => 13,
            'question' => 'Để chạy (thực thi) trang ASP .NET bạn cần có tối thiểu?',
                'answerA' => 'Java Virtual Machine',
                'answerB' => 'Windows explorer',
                'answerC' => 'Common Language',
                'answerD' => 'Một trình duyệt Web',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 178,
                'created_by' => 13,
                'question' => 'PostBack có cho Form nào dưới đây',
                'answerA' => ' Winforms',
                'answerB' => 'HTMLForms',
                'answerC' => 'Webforms',
                'answerD' => 'Cả 3 câu a,b,c đều đúng',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 179,
                'created_by' => 13,
                'question' => 'Ứng dụng web ?',
                'answerA' => 'Chỉ chạy trên một máy đơn',
                'answerB' => 'Có kiến trúc Client/Server',
                'answerC' => 'Là tất cả ứng dụng có sử dụng Internet',
                'answerD' => 'Cả 2 câu a và b đều sai',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 180,
                'created_by' => 13,
                'question' => 'Địa chỉ URL của ứng dụng web được xác định bởi ?',
                'answerA' => 'Thư mục ảo của ứng dụng',
                'answerB' => 'Thư mục vật lý của ứng dụng',
                'answerC' => 'Tên của Project',
                'answerD' => 'Cả 3 câu đều sai',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 181,
                'created_by' => 13,
                'question' => 'Phát biểu nào đúng ?',
                'answerA' => 'Phần thực thi của ứng dụng web chạy dưới sự điều khiển của web server',
                'answerB' => 'Thông tin được truyền từ server đến client bằng giao thức FTP',
                'answerC' => 'Ứng dụng web không cần phải cài đặt trên phía client',
                'answerD' => 'Dịch vụ web là một loại ứng dụng Internet',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 182,
                'created_by' => 13,
            'question' => 'Để chạy (thực thi) trang ASP .NET bạn cần có tối thiểu?',
                'answerA' => 'Java Virtual Machine',
                'answerB' => 'Windows explorer',
                'answerC' => 'Common Language',
                'answerD' => 'Một trình duyệt Web',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 183,
                'created_by' => 13,
                'question' => 'PostBack có cho Form nào dưới đây',
                'answerA' => ' Winforms',
                'answerB' => 'HTMLForms',
                'answerC' => 'Webforms',
                'answerD' => 'Cả 3 câu a,b,c đều đúng',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 184,
                'created_by' => 13,
                'question' => 'Ứng dụng web ?',
                'answerA' => 'Chỉ chạy trên một máy đơn',
                'answerB' => 'Có kiến trúc Client/Server',
                'answerC' => 'Là tất cả ứng dụng có sử dụng Internet',
                'answerD' => 'Cả 2 câu a và b đều sai',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 185,
                'created_by' => 13,
                'question' => 'Địa chỉ URL của ứng dụng web được xác định bởi ?',
                'answerA' => 'Thư mục ảo của ứng dụng',
                'answerB' => 'Thư mục vật lý của ứng dụng',
                'answerC' => 'Tên của Project',
                'answerD' => 'Cả 3 câu đều sai',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 186,
                'created_by' => 13,
                'question' => 'Phát biểu nào đúng ?',
                'answerA' => 'Phần thực thi của ứng dụng web chạy dưới sự điều khiển của web server',
                'answerB' => 'Thông tin được truyền từ server đến client bằng giao thức FTP',
                'answerC' => 'Ứng dụng web không cần phải cài đặt trên phía client',
                'answerD' => 'Dịch vụ web là một loại ứng dụng Internet',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 187,
                'created_by' => 13,
            'question' => 'Để chạy (thực thi) trang ASP .NET bạn cần có tối thiểu?',
                'answerA' => 'Java Virtual Machine',
                'answerB' => 'Windows explorer',
                'answerC' => 'Common Language',
                'answerD' => 'Một trình duyệt Web',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 188,
                'created_by' => 13,
                'question' => 'PostBack có cho Form nào dưới đây',
                'answerA' => ' Winforms',
                'answerB' => 'HTMLForms',
                'answerC' => 'Webforms',
                'answerD' => 'Cả 3 câu a,b,c đều đúng',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 189,
                'created_by' => 13,
                'question' => 'Ứng dụng web ?',
                'answerA' => 'Chỉ chạy trên một máy đơn',
                'answerB' => 'Có kiến trúc Client/Server',
                'answerC' => 'Là tất cả ứng dụng có sử dụng Internet',
                'answerD' => 'Cả 2 câu a và b đều sai',
                'correctAnswer' => 'B',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 190,
                'created_by' => 13,
                'question' => 'Địa chỉ URL của ứng dụng web được xác định bởi ?',
                'answerA' => 'Thư mục ảo của ứng dụng',
                'answerB' => 'Thư mục vật lý của ứng dụng',
                'answerC' => 'Tên của Project',
                'answerD' => 'Cả 3 câu đều sai',
                'correctAnswer' => 'B',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 191,
                'created_by' => 13,
                'question' => 'Phát biểu nào đúng ?',
                'answerA' => 'Phần thực thi của ứng dụng web chạy dưới sự điều khiển của web server',
                'answerB' => 'Thông tin được truyền từ server đến client bằng giao thức FTP',
                'answerC' => 'Ứng dụng web không cần phải cài đặt trên phía client',
                'answerD' => 'Dịch vụ web là một loại ứng dụng Internet',
                'correctAnswer' => 'B',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 192,
                'created_by' => 13,
            'question' => 'Để chạy (thực thi) trang ASP .NET bạn cần có tối thiểu?',
                'answerA' => 'Java Virtual Machine',
                'answerB' => 'Windows explorer',
                'answerC' => 'Common Language',
                'answerD' => 'Một trình duyệt Web',
                'correctAnswer' => 'B',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 4,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 193,
                'created_by' => 13,
                'question' => 'PostBack có cho Form nào dưới đây',
                'answerA' => ' Winforms',
                'answerB' => 'HTMLForms',
                'answerC' => 'Webforms',
                'answerD' => 'Cả 3 câu a,b,c đều đúng',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 194,
                'created_by' => 13,
                'question' => 'Ứng dụng web ?',
                'answerA' => 'Chỉ chạy trên một máy đơn',
                'answerB' => 'Có kiến trúc Client/Server',
                'answerC' => 'Là tất cả ứng dụng có sử dụng Internet',
                'answerD' => 'Cả 2 câu a và b đều sai',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 195,
                'created_by' => 13,
                'question' => 'Địa chỉ URL của ứng dụng web được xác định bởi ?',
                'answerA' => 'Thư mục ảo của ứng dụng',
                'answerB' => 'Thư mục vật lý của ứng dụng',
                'answerC' => 'Tên của Project',
                'answerD' => 'Cả 3 câu đều sai',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 196,
                'created_by' => 13,
                'question' => 'Phát biểu nào đúng ?',
                'answerA' => 'Phần thực thi của ứng dụng web chạy dưới sự điều khiển của web server',
                'answerB' => 'Thông tin được truyền từ server đến client bằng giao thức FTP',
                'answerC' => 'Ứng dụng web không cần phải cài đặt trên phía client',
                'answerD' => 'Dịch vụ web là một loại ứng dụng Internet',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 197,
                'created_by' => 13,
            'question' => 'Để chạy (thực thi) trang ASP .NET bạn cần có tối thiểu?',
                'answerA' => 'Java Virtual Machine',
                'answerB' => 'Windows explorer',
                'answerC' => 'Common Language',
                'answerD' => 'Một trình duyệt Web',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 198,
                'created_by' => 13,
                'question' => 'PostBack có cho Form nào dưới đây',
                'answerA' => ' Winforms',
                'answerB' => 'HTMLForms',
                'answerC' => 'Webforms',
                'answerD' => 'Cả 3 câu a,b,c đều đúng',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 199,
                'created_by' => 13,
                'question' => 'Ứng dụng web ?',
                'answerA' => 'Chỉ chạy trên một máy đơn',
                'answerB' => 'Có kiến trúc Client/Server',
                'answerC' => 'Là tất cả ứng dụng có sử dụng Internet',
                'answerD' => 'Cả 2 câu a và b đều sai',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 200,
                'created_by' => 13,
                'question' => 'Địa chỉ URL của ứng dụng web được xác định bởi ?',
                'answerA' => 'Thư mục ảo của ứng dụng',
                'answerB' => 'Thư mục vật lý của ứng dụng',
                'answerC' => 'Tên của Project',
                'answerD' => 'Cả 3 câu đều sai',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 201,
                'created_by' => 13,
                'question' => 'Phát biểu nào đúng ?',
                'answerA' => 'Phần thực thi của ứng dụng web chạy dưới sự điều khiển của web server',
                'answerB' => 'Thông tin được truyền từ server đến client bằng giao thức FTP',
                'answerC' => 'Ứng dụng web không cần phải cài đặt trên phía client',
                'answerD' => 'Dịch vụ web là một loại ứng dụng Internet',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 202,
                'created_by' => 13,
            'question' => 'Để chạy (thực thi) trang ASP .NET bạn cần có tối thiểu?',
                'answerA' => 'Java Virtual Machine',
                'answerB' => 'Windows explorer',
                'answerC' => 'Common Language',
                'answerD' => 'Một trình duyệt Web',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 5,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 203,
                'created_by' => 13,
                'question' => 'Hệ điều hành là chương trình hoạt động giữa người sử dụng với :',
                'answerA' => 'Phần mềm của máy tính',
                'answerB' => 'Phần cứng của máy tính',
                'answerC' => 'Các chương trình ứng dụng',
                'answerD' => 'CPU và bộ nhớ',
                'correctAnswer' => 'B',
                'hint' => NULL,
                'mark' => 1,
            'explanation' => 'Hệ điều hành (tiếng Anh: Operating System - viết tắt: OS) là một phần mềm dùng để điều hành, quản lý toàn bộ tất cả thành phần (bao gồm cả phần cứng và phần mềm) của thiết bị điện tử.Có vai trò trung gian trong việc giao tiếp giữa người sử dụng và thiết b',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 204,
                'created_by' => 13,
                'question' => 'Lời gọi hệ thống là lệnh do hệ điều hành cung cấp dùng để giao tiếp giữa hệ điều hành và:',
                'answerA' => 'Tiến trình',
                'answerB' => 'Chương trình ứng dụng',
                'answerC' => 'Phần cứng máy tính',
                'answerD' => 'Người sử dụng',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
            'explanation' => 'Trong máy tính, một lời gọi hệ thống là việc một chương trình máy tính yêu cầu một dịch vụ từ nhân của hệ điều hành mà nó được thực thi. Điều này có thể bao gồm các dịch vụ liên quan đến phần cứng (ví dụ: truy cập ổ đĩa cứng), tạo và thực thi các tiến trì',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 205,
                'created_by' => 13,
                'question' => 'Trong các cấu trúc của hệ điều hành sau đây cấu trúc nào tương thích dễ dàng với mô hình hệ thống phân tán',
                'answerA' => 'Cấu trúc đơn giản',
                'answerB' => 'Cấu trúc theo lớp',
                'answerC' => 'Cấu trúc máy ảo',
                'answerD' => 'Cấu trúc Servicer-client',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Kiến trúc này có nhiều điểm tương đồng với kiến trúc Client - Server',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 206,
                'created_by' => 13,
                'question' => 'Câu nào sau đây là không chính xác :',
                'answerA' => 'Tiến trình là một chương trình đang ở trong bộ nhớ',
                'answerB' => 'Tiến trình là một chương trình đang xử lí, sở hữu một không gian địa chỉ, một con trỏ lệnh, một tập các thanh ghi và stack',
                'answerC' => 'Tiến trình tự quyết định thời điểm cần dừng hoạt động đang xử lí để phục vụ tiến trình khác.',
                'answerD' => 'Các tiến trình có thể liên lạc với nhau không thông qua hệ điều hành.',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Tiến trình không thể tự quyết định thời điểm cần dừng hoạt động đang xử lí để phục vụ tiến trình khác và không thể liên lạc với nhau',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 207,
                'created_by' => 13,
                'question' => 'Khi một tiến trình người dùng gọi đến một lời gọi hệ thống, tiến trình của hệ điều hành xử lí lời gọi này hoạt động theo chế độ:',
                'answerA' => 'Không đặc quyền',
                'answerB' => 'Đặc quyền',
                'answerC' => 'Không câu nào đúng',
                'answerD' => 'Cả a và b',
                'correctAnswer' => 'B',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Chế độ đặc quyền đc sử dụng khi có 1 lời gọi hệ thống từ người dùng',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 208,
                'created_by' => 13,
                'question' => 'Giả tiến trình A sinh ra tiểu trình B, C, câu nào sau đây là không chính xác :',
                'answerA' => 'Tiểu trình B và C không sử chung con trỏ lệnh',
                'answerB' => 'Tiểu trình B và C không sử chung không sử chung tập thanh ghi',
                'answerC' => 'Tiểu trình B và C không sử chung stack',
                'answerD' => 'Tiểu trình B và C không sử chung không gian địa chỉ.',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Tiểu trình B và C được sinh ra bới tiến trình A hoàn toàn có thế dùng chung không gian địa chỉ',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 209,
                'created_by' => 13,
                'question' => 'Giải thuật điều phối đơn giản và dễ cài đặt nhưng không thích hợp với các hệ thống nhiều người dùng thuộc loại :',
                'answerA' => 'Điều phối độc quyền',
                'answerB' => 'Điều phối không độc quyền',
                'answerC' => 'Không câu nào đúng',
                'answerD' => 'Cả hai câu đều đúng',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Do điều phối độc quyền chỉ thích hợp cho hệ thống đơn người dùng',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 210,
                'created_by' => 13,
                'question' => 'Nguyên lí phân phối độc quyền thường thích hợp với các hệ xử lí :',
                'answerA' => 'Hệ thống xử lí theo thời gian thực',
                'answerB' => 'Hệ thống đa chương',
                'answerC' => 'Hệ thống chia sẻ tương tác',
                'answerD' => 'Hệ thống xử lí theo lô',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Hệ thống xử lí theo lô yêu cầu cần phải xử lý khá phứp tạp,,điều này nguyên lý phân phối độc quyền hoàn toàn có thể đáp ứng',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 211,
                'created_by' => 13,
                'question' => 'Chức năng điều phối tác vụ của hệ điều hành được kích hoạt khi :',
                'answerA' => 'Hệ thống tạo lập một tiến trình',
                'answerB' => 'Tiến trình kết thúc xử lí',
                'answerC' => 'Xảy ra ngắt',
                'answerD' => 'Câu a,b đúng',
                'correctAnswer' => 'D',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => 'Khi hệ thống tạo 1 tiến trình và khi tiến trình kết thúc đều yêu cầu hệ điều hành cần kích hoạt chứ năng điều phối tác vụ',
                'exam_id' => 2,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 212,
                'created_by' => 13,
                'question' => 'PostBack có cho Form nào dưới đây',
                'answerA' => ' Winforms',
                'answerB' => 'HTMLForms',
                'answerC' => 'Webforms',
                'answerD' => 'Cả 3 câu a,b,c đều đúng',
                'correctAnswer' => 'C',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 3,
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 233,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 1',
                'answerA' => 'Đáp án A : Câu 1',
                'answerB' => 'Đáp án B : Câu 1',
                'answerC' => 'Đáp án C : Câu 1',
                'answerD' => 'Đáp án D : Câu 1',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 234,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 2',
                'answerA' => 'Đáp án A : Câu 2',
                'answerB' => 'Đáp án B : Câu 2',
                'answerC' => 'Đáp án C : Câu 2',
                'answerD' => 'Đáp án D : Câu 2',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 235,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 3',
                'answerA' => 'Đáp án A : Câu 3',
                'answerB' => 'Đáp án B : Câu 3',
                'answerC' => 'Đáp án C : Câu 3',
                'answerD' => 'Đáp án D : Câu 3',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 236,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 4',
                'answerA' => 'Đáp án A : Câu 4',
                'answerB' => 'Đáp án B : Câu 4',
                'answerC' => 'Đáp án C : Câu 4',
                'answerD' => 'Đáp án D : Câu 4',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 237,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 5',
                'answerA' => 'Đáp án A : Câu 5',
                'answerB' => 'Đáp án B : Câu 5',
                'answerC' => 'Đáp án C : Câu 5',
                'answerD' => 'Đáp án D : Câu 5',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 238,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 6',
                'answerA' => 'Đáp án A : Câu 6',
                'answerB' => 'Đáp án B : Câu 6',
                'answerC' => 'Đáp án C : Câu 6',
                'answerD' => 'Đáp án D : Câu 6',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 239,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 7',
                'answerA' => 'Đáp án A : Câu 7',
                'answerB' => 'Đáp án B : Câu 7',
                'answerC' => 'Đáp án C : Câu 7',
                'answerD' => 'Đáp án D : Câu 7',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 240,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 8',
                'answerA' => 'Đáp án A : Câu 8',
                'answerB' => 'Đáp án B : Câu 8',
                'answerC' => 'Đáp án C : Câu 8',
                'answerD' => 'Đáp án D : Câu 8',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 241,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 9',
                'answerA' => 'Đáp án A : Câu 9',
                'answerB' => 'Đáp án B : Câu 9',
                'answerC' => 'Đáp án C : Câu 9',
                'answerD' => 'Đáp án D : Câu 9',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 242,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 10',
                'answerA' => 'Đáp án A : Câu 10',
                'answerB' => 'Đáp án B : Câu 10',
                'answerC' => 'Đáp án C : Câu 10',
                'answerD' => 'Đáp án D : Câu 10',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:23:48',
                'updated_at' => '2022-02-24 21:23:48',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 243,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 1',
                'answerA' => 'Đáp án A : Câu 1',
                'answerB' => 'Đáp án B : Câu 1',
                'answerC' => 'Đáp án C : Câu 1',
                'answerD' => 'Đáp án D : Câu 1',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 244,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 2',
                'answerA' => 'Đáp án A : Câu 2',
                'answerB' => 'Đáp án B : Câu 2',
                'answerC' => 'Đáp án C : Câu 2',
                'answerD' => 'Đáp án D : Câu 2',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 245,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 3',
                'answerA' => 'Đáp án A : Câu 3',
                'answerB' => 'Đáp án B : Câu 3',
                'answerC' => 'Đáp án C : Câu 3',
                'answerD' => 'Đáp án D : Câu 3',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 246,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 4',
                'answerA' => 'Đáp án A : Câu 4',
                'answerB' => 'Đáp án B : Câu 4',
                'answerC' => 'Đáp án C : Câu 4',
                'answerD' => 'Đáp án D : Câu 4',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 247,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 5',
                'answerA' => 'Đáp án A : Câu 5',
                'answerB' => 'Đáp án B : Câu 5',
                'answerC' => 'Đáp án C : Câu 5',
                'answerD' => 'Đáp án D : Câu 5',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 248,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 6',
                'answerA' => 'Đáp án A : Câu 6',
                'answerB' => 'Đáp án B : Câu 6',
                'answerC' => 'Đáp án C : Câu 6',
                'answerD' => 'Đáp án D : Câu 6',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 249,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 7',
                'answerA' => 'Đáp án A : Câu 7',
                'answerB' => 'Đáp án B : Câu 7',
                'answerC' => 'Đáp án C : Câu 7',
                'answerD' => 'Đáp án D : Câu 7',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 250,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 8',
                'answerA' => 'Đáp án A : Câu 8',
                'answerB' => 'Đáp án B : Câu 8',
                'answerC' => 'Đáp án C : Câu 8',
                'answerD' => 'Đáp án D : Câu 8',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 251,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 9',
                'answerA' => 'Đáp án A : Câu 9',
                'answerB' => 'Đáp án B : Câu 9',
                'answerC' => 'Đáp án C : Câu 9',
                'answerD' => 'Đáp án D : Câu 9',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 252,
                'created_by' => 13,
                'question' => 'Câu hỏi thứ 10',
                'answerA' => 'Đáp án A : Câu 10',
                'answerB' => 'Đáp án B : Câu 10',
                'answerC' => 'Đáp án C : Câu 10',
                'answerD' => 'Đáp án D : Câu 10',
                'correctAnswer' => 'A',
                'hint' => NULL,
                'mark' => 1,
                'explanation' => NULL,
                'exam_id' => 14,
                'created_at' => '2022-02-24 21:30:30',
                'updated_at' => '2022-02-24 21:30:30',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}