<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'fullname' => 'Prof. Monroe Gaylord I',
                'email' => 'vonrueden.georgette@example.net',
                'pays' => 'Niue',
                'genre' => 'Female',
                'ville_residence' => 'South Zorahaven',
                'telephone' => '+1-915-656-4623',
                'biographie' => 'Eos ut deleniti ea repudiandae quaerat eos qui. Ratione consectetur sint modi amet deserunt nesciunt non. Distinctio distinctio molestiae nulla.',
                'newsletter' => 0,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'teacher',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Fugit91',
                'avatar' => 'avatar/default.png',
                'remember_token' => '3FfabYIbwgly1KohVGjJ',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'fullname' => 'Ernesto Mosciski',
                'email' => 'renner.lauren@example.com',
                'pays' => 'Andorra',
                'genre' => 'Female',
                'ville_residence' => 'Flossieberg',
                'telephone' => '743.835.9701',
                'biographie' => 'Quis doloribus laborum corrupti et tenetur in. Expedita nihil nemo placeat eum cum quidem at. Sed nemo minus adipisci temporibus voluptatum. Aut tempora temporibus magnam delectus molestiae.',
                'newsletter' => 1,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'student',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Ipsam154',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'X53xTFtKMi5BQ2Q6iG32',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'fullname' => 'Marquis McDermott',
                'email' => 'sydni37@example.org',
                'pays' => 'Luxembourg',
                'genre' => 'Female',
                'ville_residence' => 'South Alene',
                'telephone' => '608-643-2564',
                'biographie' => 'Rem repudiandae deleniti occaecati deleniti molestias consequatur. Optio quos itaque magni. Quis dolores cum quidem non vel omnis.',
                'newsletter' => 0,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'teacher',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Quidem194',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'TEd4smA54q6wBBWIa28G',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'fullname' => 'Dr. Jayda Hermann',
                'email' => 'kemmer.adrian@example.com',
                'pays' => 'Qatar',
                'genre' => 'Female',
                'ville_residence' => 'West Allanborough',
                'telephone' => '1-860-863-9231',
                'biographie' => 'Alias ut esse nostrum aut. Delectus voluptate incidunt consequatur quae. Quaerat sit soluta omnis molestiae. Ipsum est quis fugit minima id. Possimus et saepe excepturi ex sed aut.',
                'newsletter' => 1,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'student',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Sint6',
                'avatar' => 'avatar/default.png',
                'remember_token' => '8nUsCbM15LIKgduuE2xU',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'fullname' => 'Ms. Lina Carter V',
                'email' => 'urath@example.org',
                'pays' => 'Grenada',
                'genre' => 'Female',
                'ville_residence' => 'East Jeradville',
            'telephone' => '(715) 341-4942',
                'biographie' => 'Atque et voluptatem ut. Voluptas voluptatem voluptates et doloremque impedit consequuntur. Qui doloremque molestiae ut est nihil facilis libero. Iure nisi sit explicabo sint est aperiam natus.',
                'newsletter' => 1,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'administrator',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Commodi93',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'VKGspkNYxus9Ynw4hr6O',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'fullname' => 'Gwendolyn Rohan',
                'email' => 'rwest@example.org',
                'pays' => 'Macao',
                'genre' => 'Female',
                'ville_residence' => 'New Mabel',
                'telephone' => '+1-952-818-8601',
                'biographie' => 'Autem ut ut debitis aut. Ea sit cum iure magnam numquam non. Qui quisquam nisi ut non aut. Voluptas vero officiis rerum laborum vitae earum optio ipsam.',
                'newsletter' => 0,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'teacher',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Rerum154',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'gcRfwgTtzig14wMhauiX',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'fullname' => 'Jean Koss',
                'email' => 'fletcher06@example.org',
                'pays' => 'El Salvador',
                'genre' => 'Female',
                'ville_residence' => 'Columbusmouth',
                'telephone' => '952-628-5340',
                'biographie' => 'Adipisci esse est voluptatibus non. Accusantium sit pariatur minus neque incidunt. Tenetur esse dolorem similique sapiente id ut voluptatem.',
                'newsletter' => 0,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'student',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Possimus28',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'q1hNbAdZMqMF6yuz30ex',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'fullname' => 'Jett Schuppe',
                'email' => 'maggio.jasen@example.net',
                'pays' => 'Benin',
                'genre' => 'Female',
                'ville_residence' => 'New Krista',
                'telephone' => '781.333.0767',
                'biographie' => 'Rem et rerum delectus est non voluptas. Et inventore excepturi illum et tempora. Et qui blanditiis harum officiis quod.',
                'newsletter' => 0,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'administrator',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Ratione43',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'AFYnAggnxH5Y0wixhFBL',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'fullname' => 'Vallie Weimann',
                'email' => 'schinner.charley@example.net',
                'pays' => 'Slovenia',
                'genre' => 'Female',
                'ville_residence' => 'Schillerstad',
            'telephone' => '(364) 305-4628',
                'biographie' => 'Atque voluptate voluptatem occaecati facere ab. Neque eaque assumenda optio quis. Omnis eius quam sed sint perspiciatis illo quibusdam quas.',
                'newsletter' => 0,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'administrator',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Voluptas60',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'UTUvM3zjJjKyv01yzYgv',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'fullname' => 'Dr. Jonathan Beier',
                'email' => 'fkozey@example.org',
                'pays' => 'Finland',
                'genre' => 'Female',
                'ville_residence' => 'West Jacques',
                'telephone' => '+1-760-274-6071',
                'biographie' => 'Nesciunt veritatis velit magnam aspernatur reiciendis rerum. Soluta id odio quas et nisi. Ex quis voluptatum architecto nisi quae vitae.',
                'newsletter' => 1,
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'role' => 'teacher',
                'email_verified_at' => '2022-01-29 15:36:35',
                'name' => 'Et114',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'TWeVfOsc1gwT5tV60t6H',
                'created_at' => '2022-01-29 15:36:35',
                'updated_at' => '2022-01-29 15:36:35',
                'permissions' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'fullname' => 'VU THANH DAT',
                'email' => 'dat2611gd@gmail.com',
                'pays' => 'cameroun',
                'genre' => 'male',
                'ville_residence' => NULL,
                'telephone' => '+840869659930',
                'biographie' => NULL,
                'newsletter' => 0,
                'password' => '$2y$10$Y3JCr5KY9eaflnS6Zj.dGOuTXsPAWT0Dtob/IrHZNlfo5yEh3xUrG',
                'role' => 'student',
                'email_verified_at' => NULL,
                'name' => 'dat2611',
                'avatar' => 'avatar/other/23.png',
                'remember_token' => 'bXOgbJQkMCnY2gfjjDhvnniA1EqKbCWH1EZHB5WgKwycssbJsoOd1aPq4IaM',
                'created_at' => '2022-01-29 16:19:46',
                'updated_at' => '2022-01-29 16:42:40',
                'permissions' => '{"platform.systems.attachment":"0","platform.systems.roles":"0","platform.systems.users":"0","platform.index":"0"}',
            ),
            11 => 
            array (
                'id' => 13,
                'fullname' => NULL,
                'email' => 'admin@admin.com',
                'pays' => NULL,
                'genre' => 'Female',
                'ville_residence' => NULL,
                'telephone' => NULL,
                'biographie' => NULL,
                'newsletter' => 0,
                'password' => '$2y$10$6a0dh7mvpB95XNXbBBTO5Ob4D/IDCMmnVJoUdsg0tODkuOguxZkrq',
                'role' => 'student',
                'email_verified_at' => NULL,
                'name' => 'admin',
                'avatar' => 'avatar/default.png',
                'remember_token' => 'nCnIzifXTqEKmevDyWg9WpUbq8d34lzthwKfa66YbQYUyUH906L7Gq0jcI04',
                'created_at' => '2022-01-29 16:38:53',
                'updated_at' => '2022-01-29 16:42:49',
                'permissions' => '{"platform.systems.attachment":"1","platform.systems.roles":"1","platform.systems.users":"1","platform.index":"1"}',
            ),
        ));
        
        
    }
}